Try updating until successful

diff --git a/src/usr/bin/conanexiles_controller b/src/usr/bin/conanexiles_controller
--- a/src/usr/bin/conanexiles_controller
+++ b/src/usr/bin/conanexiles_controller
@@ -11,9 +11,9 @@ function get_available_build() {
 
     # get available build id and return it
     local _build_id=$(/steamcmd/steamcmd.sh +login anonymous +app_info_update 1 +app_info_print $APPID +quit | \
-    			    grep -EA 1000 "^\s+\"branches\"$" | grep -EA 5 "^\s+\"public\"$" | \
-    			    grep -m 1 -EB 10 "^\s+}" | grep -E "^\s+\"buildid\"\s+" | \
-    			    tr '[:blank:]"' ' ' | awk '{print $2}')
+        grep -EA 1000 "^\s+\"branches\"$" | grep -EA 5 "^\s+\"public\"$" | \
+        grep -m 1 -EB 10 "^\s+}" | grep -E "^\s+\"buildid\"\s+" | \
+        tr '[:blank:]"' ' ' | awk '{print $2}')
 
     echo "$_build_id"
 }
@@ -21,7 +21,7 @@ function get_available_build() {
 function get_installed_build() {
     # get currently installed build id and return it
     local _build_id=$(cat /conanexiles/steamapps/appmanifest_$APPID.acf | \
-              grep -E "^\s+\"buildid\"" |  tr '[:blank:]"' ' ' | awk '{print $2}')
+        grep -E "^\s+\"buildid\"" |  tr '[:blank:]"' ' ' | awk '{print $2}')
 
     echo "$_build_id"
 }
@@ -36,7 +36,7 @@ check_server_running() {
 
 function start_server() {
     # check if server is already running to avoid running it more than one time
-    if [[ $(check_server_running) == 0 ]];then
+    if [[ $(check_server_running) == 0 ]]; then
         notifier_error "The server is already running. I don't want to start it twice."
         return
     else
@@ -51,9 +51,9 @@ function stop_server() {
     [[ $? == 0 ]] && supervisorctl stop conanexilesServer
 
     # wait until the server process is gone
-    while ps axg | grep -F 'ConanSandboxServer' | grep -v -F 'grep' > /dev/null; do 
-      notifier_error "Seems I can't stop the server. Help me!"
-      sleep 5
+    while ps axg | grep -F 'ConanSandboxServer' | grep -v -F 'grep' > /dev/null; do
+        notifier_error "Seems I can't stop the server. Help me!"
+        sleep 5
     done
 }
 
@@ -69,17 +69,17 @@ function backup_server() {
     local _dst="/conanexiles/ConanSandbox/Saved.$(get_installed_build)"
 
     # remove backup dir if already exists (should never happen)
-    if [ -d "$_dst" ]; then
+    if [[ -d "$_dst" ]]; then
         rm -rf "$_dst"
         notifier_info "Removed existing build backup in $_dst"
     fi
 
     # backup current build db and config
-    if [ -d "$_src" ]; then
+    if [[ -d "$_src" ]]; then
         cp -a "$_src" "$_dst"
 
-        # Was backup successfull ?
-        if [ $? -eq 0 ]; then
+        # Was backup successful?
+        if [[ $? -eq 0 ]]; then
             notifier_info "Backed up current build db and configs to $_dst"
         else
             notifier_warn "Failed to backup current build db and configs to $_dst."
@@ -92,7 +92,7 @@ start_shutdown_timer() {
     _i=0
 
     while true; do
-        if [ $_i == "$_t_val" ]; then
+        if [[ "$_i" == "$_t_val" ]]; then
             break
         fi
 
@@ -102,7 +102,7 @@ start_shutdown_timer() {
             /usr/bin/rconcli broadcast --type shutdown --value $((_t_val - _i))
         fi
         sleep 60
-        ((_i++))
+        ((_i ++))
     done
 }
 
@@ -110,31 +110,35 @@ function do_update() {
     # This function take either 0 for update with sleep, or 1 for update without sleep and backup
     # stop, backup, update and start again the server
     redis_cmd_proxy redis_set_update_running_start
-    if [[ $1 == 1 ]];then
-        update_server
-    else
-        start_shutdown_timer 15
+    if [[ $1 != 1 ]]; then
+        start_shutdown_timer 10
         stop_server
         # Give other instances time to shutdown
         sleep 300
         backup_server
-        update_server
     fi
 
-    # wait till update is finished
-    while $(supervisorctl status conanexilesUpdate | grep RUNNING > /dev/null); do
-        sleep 1
+    update_server
+
+    while true; do
+        # wait till update is finished
+        while $(supervisorctl status conanexilesUpdate | grep RUNNING > /dev/null); do
+            sleep 1
+        done
+
+        local _ab=$(get_available_build)
+        local _ib=$(get_installed_build)
+
+        # Check whether there is a new version and if it differs from the installed version. This otherwise just shuts
+        # down the server and tries to update should steam be unavailable for whatever reason.
+        if [[ ! -z _ab && _ab != _ib ]]; then
+            echo "Warning: Update seems to have failed. Installed build ($_ib) does not match available build ($_ab). Trying again."
+            update_server
+        else
+            echo "Info: Updated to build ($_ib) successfully."
+            break
+        fi
     done
-
-    # check if server is up to date
-    local _ab=$(get_available_build)
-    local _ib=$(get_installed_build)
-
-    if [[ $_ab != "$_ib" ]];then
-        echo "Warning: Update seems to have failed. Installed build ($_ib) does not match available build ($_ab)."
-    else
-        echo "Info: Updated to build ($_ib) successfully."
-    fi
 
     redis_cmd_proxy redis_set_update_running_stop
 
@@ -142,12 +146,11 @@ function do_update() {
 }
 
 start_master_loop() {
-
     notifier_info "Mode: Master - Instance: $(hostname)"
 
     while true; do
         # if initial install/update fails try again
-        if [ ! -f "/conanexiles/ConanSandbox/Binaries/Win64/ConanSandboxServer-Win64-Test.exe" ]; then
+        if [[ ! -f "/conanexiles/ConanSandbox/Binaries/Win64/ConanSandboxServer-Win64-Test.exe" ]]; then
             notifier_warn "No binaries found. Doing a fresh installation"
             do_update 1
             notifier_debug "Initial installation finished."
@@ -157,7 +160,7 @@ start_master_loop() {
         ab=$(get_available_build)
         ib=$(get_installed_build)
 
-        if [[ $ab != "$ib" ]];then
+        if [[ ! -z ab && ab != ib ]]; then
             notifier_info "New build available. Updating $ib -> $ab"
             do_update 0
         fi
@@ -168,7 +171,6 @@ start_master_loop() {
 }
 
 start_slave_loop() {
-
     notifier_info "Mode: Slave - Instance: $(hostname)"
 
     while true; do
@@ -177,10 +179,9 @@ start_slave_loop() {
                 start_shutdown_timer 10
                 stop_server
             fi
-        # NOTE: We need to check this explcitly, when redis server is not accessible
+        # NOTE: We need to check this explicitly, when redis server is not accessible
         elif [[ "`redis_cmd_proxy redis_get_update_running`" == 1 ]]; then
-            [[ $(check_server_running) == 1 ]] && \
-                start_server
+            [[ $(check_server_running) == 1 ]] && start_server
         fi
         sleep 10
     done
@@ -190,9 +191,6 @@ start_slave_loop() {
 # Main loop
 #
 
-# notifier_info "Global Master Server Instance: `get_master_server_instance`"
-
-# if [[ "`get_master_server_instance`" == "`hostname`" ]];then
 if [[ "${CONANEXILES_MASTERSERVER}" == 1 ]]; then
     start_master_loop
 else
